import type { Response } from 'express';
import type { AuthenticatedRequest } from '../../shared/auth/auth.middleware.js';
import * as service from './mentor.service.js';

export const me = async (request: AuthenticatedRequest, response: Response) => response.json({ mentor: await service.profile(request.auth!.sub) });
export const programs = async (request: AuthenticatedRequest, response: Response) => response.json({ programs: await service.programs(request.auth!.sub) });
export const batches = async (request: AuthenticatedRequest, response: Response) => response.json({ batches: await service.batches(request.auth!.sub, String(request.params.programId)) });
export const overview = async (request: AuthenticatedRequest, response: Response) => response.json({ batch: await service.overview(request.auth!.sub, String(request.params.batchId)) });
export const students = async (request: AuthenticatedRequest, response: Response) => response.json({ students: await service.students(request.auth!.sub, String(request.params.batchId), String(request.query.search ?? '')) });
export const studentDetail = async (request: AuthenticatedRequest, response: Response) => response.json({ student: await service.studentDetail(request.auth!.sub, String(request.params.batchId), String(request.params.studentId)) });
export const tasks = async (request: AuthenticatedRequest, response: Response) => response.json({ tasks: await service.tasks(request.auth!.sub, String(request.params.batchId)) });
export const createTask = async (request: AuthenticatedRequest, response: Response) => response.status(201).json({ task: await service.createTask(request.auth!.sub, String(request.params.batchId), request.body) });
export const updateTask = async (request: AuthenticatedRequest, response: Response) => response.json({ task: await service.updateTask(request.auth!.sub, String(request.params.taskId), request.body) });
export const sessions = async (request: AuthenticatedRequest, response: Response) => response.json({ sessions: await service.sessions(request.auth!.sub, String(request.params.batchId)) });
export const createSession = async (request: AuthenticatedRequest, response: Response) => response.status(201).json({ session: await service.createSession(request.auth!.sub, String(request.params.batchId), request.body) });
export const updateSession = async (request: AuthenticatedRequest, response: Response) => response.json({ session: await service.updateSession(request.auth!.sub, String(request.params.sessionId), request.body) });
export const notices = async (request: AuthenticatedRequest, response: Response) => response.json({ notices: await service.notices(request.auth!.sub, String(request.params.batchId)) });
export const createNotice = async (request: AuthenticatedRequest, response: Response) => response.status(201).json({ notice: await service.createNotice(request.auth!.sub, String(request.params.batchId), request.body) });
export const updateNotice = async (request: AuthenticatedRequest, response: Response) => response.json({ notice: await service.updateNotice(request.auth!.sub, String(request.params.noticeId), request.body) });
export const doubts = async (request: AuthenticatedRequest, response: Response) => response.json({ doubts: await service.doubts(request.auth!.sub, String(request.params.batchId), { status: String(request.query.status ?? ''), visibility: String(request.query.visibility ?? ''), search: String(request.query.search ?? '') }) });
export const replies = async (request: AuthenticatedRequest, response: Response) => response.json({ replies: await service.replies(request.auth!.sub, String(request.params.doubtId), request.query.parentReplyId ? String(request.query.parentReplyId) : null, Number(request.query.take ?? 3), Number(request.query.skip ?? 0)) });
export const addReply = async (request: AuthenticatedRequest, response: Response) => response.status(201).json({ reply: await service.addReply(request.auth!.sub, String(request.params.doubtId), request.body) });
export const setDoubtStatus = async (request: AuthenticatedRequest, response: Response) => response.json({ doubt: await service.setDoubtStatus(request.auth!.sub, String(request.params.doubtId), request.body.status) });
export const setDoubtPinned = async (request: AuthenticatedRequest, response: Response) => response.json({ doubt: await service.setDoubtPinned(request.auth!.sub, String(request.params.doubtId), request.body.isPinned) });
export const setReplyPinned = async (request: AuthenticatedRequest, response: Response) => response.json({ reply: await service.setReplyPinned(request.auth!.sub, String(request.params.replyId), request.body.isPinned) });
export const tests = async (request: AuthenticatedRequest, response: Response) => response.json({ tests: await service.tests(request.auth!.sub, String(request.params.batchId)) });
export const testDetail = async (request: AuthenticatedRequest, response: Response) => response.json({ test: await service.testDetail(request.auth!.sub, String(request.params.testId)) });
export const createTest = async (request: AuthenticatedRequest, response: Response) => response.status(201).json({ test: await service.createTest(request.auth!.sub, String(request.params.batchId), request.body) });
export const updateTest = async (request: AuthenticatedRequest, response: Response) => response.json({ test: await service.updateTest(request.auth!.sub, String(request.params.testId), request.body) });
export const createSection = async (request: AuthenticatedRequest, response: Response) => response.status(201).json({ section: await service.createSection(request.auth!.sub, String(request.params.testId), request.body) });
export const createComprehension = async (request: AuthenticatedRequest, response: Response) => response.status(201).json({ comprehension: await service.createComprehension(request.auth!.sub, request.body) });
export const createQuestion = async (request: AuthenticatedRequest, response: Response) => response.status(201).json({ question: await service.createQuestion(request.auth!.sub, request.body) });
export const masters = async (_request: AuthenticatedRequest, response: Response) => response.json(await service.masters());
export const attemptAnalysis = async (request: AuthenticatedRequest, response: Response) => response.json({ analysis: await service.attemptAnalysis(request.auth!.sub, String(request.params.attemptId)) });
