import { Router } from 'express';
import { requireMentor } from '../../shared/auth/auth.middleware.js';
import { validateBody } from '../../shared/http/validate.js';
import * as controller from './mentor.controller.js';
import { comprehensionSchema, doubtStatusSchema, noticeSchema, pinSchema, questionSchema, replySchema, sectionSchema, sessionSchema, taskSchema, testSchema } from './mentor.schemas.js';

export const mentorRouter = Router();

mentorRouter.use(requireMentor);
mentorRouter.get('/me', controller.me);
mentorRouter.get('/masters', controller.masters);
mentorRouter.get('/programs', controller.programs);
mentorRouter.get('/programs/:programId/batches', controller.batches);
mentorRouter.get('/batches/:batchId', controller.overview);
mentorRouter.get('/batches/:batchId/students', controller.students);
mentorRouter.get('/batches/:batchId/students/:studentId', controller.studentDetail);
mentorRouter.get('/batches/:batchId/tasks', controller.tasks);
mentorRouter.post('/batches/:batchId/tasks', validateBody(taskSchema), controller.createTask);
mentorRouter.put('/tasks/:taskId', validateBody(taskSchema), controller.updateTask);
mentorRouter.get('/batches/:batchId/sessions', controller.sessions);
mentorRouter.post('/batches/:batchId/sessions', validateBody(sessionSchema), controller.createSession);
mentorRouter.put('/sessions/:sessionId', validateBody(sessionSchema), controller.updateSession);
mentorRouter.get('/batches/:batchId/notices', controller.notices);
mentorRouter.post('/batches/:batchId/notices', validateBody(noticeSchema), controller.createNotice);
mentorRouter.put('/notices/:noticeId', validateBody(noticeSchema), controller.updateNotice);
mentorRouter.get('/batches/:batchId/doubts', controller.doubts);
mentorRouter.get('/doubts/:doubtId/replies', controller.replies);
mentorRouter.post('/doubts/:doubtId/replies', validateBody(replySchema), controller.addReply);
mentorRouter.patch('/doubts/:doubtId/status', validateBody(doubtStatusSchema), controller.setDoubtStatus);
mentorRouter.patch('/doubts/:doubtId/pinned', validateBody(pinSchema), controller.setDoubtPinned);
mentorRouter.patch('/replies/:replyId/pinned', validateBody(pinSchema), controller.setReplyPinned);
mentorRouter.get('/batches/:batchId/tests', controller.tests);
mentorRouter.post('/batches/:batchId/tests', validateBody(testSchema), controller.createTest);
mentorRouter.get('/tests/:testId', controller.testDetail);
mentorRouter.put('/tests/:testId', validateBody(testSchema), controller.updateTest);
mentorRouter.post('/tests/:testId/sections', validateBody(sectionSchema), controller.createSection);
mentorRouter.post('/comprehensions', validateBody(comprehensionSchema), controller.createComprehension);
mentorRouter.post('/questions', validateBody(questionSchema), controller.createQuestion);
mentorRouter.get('/attempts/:attemptId/analysis', controller.attemptAnalysis);
