import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, BookOpenCheck, Check, ChevronDown, ChevronRight, Clock3, FileText, Globe2, Layers3, Lock, PlayCircle, Sparkles, Trophy, Video } from 'lucide-react';

import { EmptyState } from '../../../components/empty-state';
import { Badge } from '../../../components/ui/badge';
import { Button } from '../../../components/ui/button';
import { Card } from '../../../components/ui/card';
import { Skeleton } from '../../../components/ui/skeleton';
import { api } from '../../../lib/api';
import { cn, formatDateTime } from '../../../lib/utils';
import type { ContentAttempt, ContentSubtopic, ContentSubject, ContentTopic, ContentTreeResponse, LearningContent } from './types';

type View = 'subjects' | 'learning' | 'attempts';
const percent = (done: number, total: number) => total ? Math.round((done / total) * 100) : 0;
const formatDuration = (seconds: number) => `${Math.floor(seconds / 60)}m ${seconds % 60}s`;
const contentVisual = { YOUTUBE: Video, PDF: FileText, DOCUMENT: BookOpenCheck, WEBSITE: Globe2 };

export const ContentPage = () => {
  const queryClient = useQueryClient();
  const [view, setView] = useState<View>('subjects');
  const [subjectId, setSubjectId] = useState<string>();
  const [topicId, setTopicId] = useState<string>();
  const learning = useQuery({ queryKey: ['learning-content'], queryFn: () => api<ContentTreeResponse>('/api/v1/content') });
  const attempts = useQuery({ queryKey: ['content-attempts'], queryFn: () => api<{ attempts: ContentAttempt[] }>('/api/v1/content/attempts'), enabled: view === 'attempts' });
  const updateCompletion = useMutation({
    mutationFn: ({ contentId, completed }: { contentId: string; completed: boolean }) => api(`/api/v1/content/contents/${contentId}/completion`, { method: 'PATCH', body: JSON.stringify({ completed }) }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['learning-content'] }),
  });
  if (learning.isLoading) return <ContentSkeleton />;
  if (learning.isError || !learning.data) return <EmptyState icon={BookOpenCheck} title="Could not load learning content" description="Please refresh the page and try again." />;
  if (!learning.data.subjects.length) return <EmptyState icon={BookOpenCheck} title="Learning library is on its way" description="There are no active learning resources yet." />;
  const subject = learning.data.subjects.find((item) => item.id === subjectId) ?? learning.data.subjects[0];
  const openSubject = (item: ContentSubject) => { setSubjectId(item.id); setTopicId(item.topics[0]?.id); setView('learning'); };
  return <div className="space-y-7">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-moss-700">Learning library</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-ink">{view === 'attempts' ? 'Practice history' : view === 'learning' ? subject.name : 'Choose a subject'}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-500">{view === 'subjects' ? 'Pick a subject to continue your structured preparation.' : view === 'attempts' ? 'Review your completed and in-progress topic test attempts.' : 'Select a topic, learn in sequence, then reinforce it with a focused practice test.'}</p></div><div className="flex gap-2">{view !== 'subjects' && <Button variant="outline" onClick={() => setView('subjects')}><ArrowLeft size={16} />All subjects</Button>}<Button variant={view === 'attempts' ? 'secondary' : 'outline'} onClick={() => setView('attempts')}><Trophy size={16} />Attempted tests</Button></div></header>
    {view === 'subjects' && <SubjectLibrary subjects={learning.data.subjects} onSelect={openSubject} />}
    {view === 'learning' && <LearningWorkspace subject={subject} topicId={topicId} onTopicChange={setTopicId} onCompletion={(contentId, completed) => updateCompletion.mutate({ contentId, completed })} saving={updateCompletion.isPending} />}
    {view === 'attempts' && <AttemptsPanel attempts={attempts} />}
  </div>;
};

const SubjectLibrary = ({ subjects, onSelect }: { subjects: ContentSubject[]; onSelect: (subject: ContentSubject) => void }) => <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{subjects.map((subject, index) => { const progress = percent(subject.completedContentCount, subject.totalContentCount); return <Card key={subject.id} className="group relative overflow-hidden p-6"><div className={cn('absolute right-0 top-0 size-28 translate-x-7 -translate-y-7 rounded-full opacity-70', index % 3 === 0 ? 'bg-lime/35' : index % 3 === 1 ? 'bg-sky-100' : 'bg-amber/20')} /><div className="relative"><div className="flex items-start justify-between gap-4"><span className="grid size-11 place-items-center rounded-2xl bg-moss-100 text-moss-800"><BookOpenCheck size={21} /></span><Badge className="bg-stone-100 text-stone-600">{subject.topics.length} topics</Badge></div><h2 className="mt-6 text-xl font-bold text-ink">{subject.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-stone-500">{subject.description}</p><div className="mt-6"><div className="flex justify-between text-xs font-semibold"><span className="text-stone-500">Your progress</span><span className="text-moss-800">{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-moss-100"><div className="h-full rounded-full bg-lime transition-all" style={{ width: `${progress}%` }} /></div><p className="mt-2 text-xs text-stone-400">{subject.completedContentCount} of {subject.totalContentCount} lessons completed</p></div><Button className="mt-6 w-full" onClick={() => onSelect(subject)}>Open {subject.name}<ChevronRight size={16} /></Button></div></Card>; })}</div>;

const LearningWorkspace = ({ subject, topicId, onTopicChange, onCompletion, saving }: { subject: ContentSubject; topicId: string | undefined; onTopicChange: (id: string) => void; onCompletion: (id: string, completed: boolean) => void; saving: boolean }) => { const topic = subject.topics.find((item) => item.id === topicId) ?? subject.topics[0]; if (!topic) return <EmptyState icon={Layers3} title="No topics available" description="Resources will appear here when this subject is published." />; return <div className="grid gap-6 xl:grid-cols-[270px_minmax(0,1fr)]"><Card className="h-fit overflow-hidden"><div className="border-b border-stone-100 px-5 py-4"><p className="text-xs font-bold uppercase tracking-[.16em] text-stone-400">{subject.name} topics</p></div><div className="p-2">{subject.topics.map((item) => <button key={item.id} onClick={() => onTopicChange(item.id)} className={cn('w-full rounded-2xl px-3 py-3 text-left transition', item.id === topic.id ? 'bg-moss-800 text-white shadow-sm' : 'text-stone-600 hover:bg-moss-50')}><span className="block text-sm font-semibold">{item.name}</span><span className={cn('mt-1 block text-xs', item.id === topic.id ? 'text-moss-100/70' : 'text-stone-400')}>{percent(item.completedContentCount, item.totalContentCount)}% complete · {item.totalContentCount} lessons</span><div className={cn('mt-2 h-1 overflow-hidden rounded-full', item.id === topic.id ? 'bg-white/15' : 'bg-stone-100')}><div className="h-full rounded-full bg-lime" style={{ width: `${percent(item.completedContentCount, item.totalContentCount)}%` }} /></div></button>)}</div></Card><div className="min-w-0 space-y-6"><div className="flex items-center gap-2 text-sm text-stone-500"><span>{subject.name}</span><ChevronRight size={15} /><span className="font-medium text-ink">{topic.name}</span></div><Card className="p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-moss-700">Current topic</p><h2 className="mt-1 text-2xl font-bold text-ink">{topic.name}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-500">{topic.description}</p></div><div className="rounded-2xl bg-moss-50 px-4 py-3 sm:min-w-36"><p className="text-xl font-bold text-moss-900">{percent(topic.completedContentCount, topic.totalContentCount)}%</p><p className="mt-1 text-xs text-moss-700">{topic.completedContentCount}/{topic.totalContentCount} lessons complete</p></div></div></Card><div className="space-y-5">{topic.subtopics.map((subtopic) => <SubtopicSection key={subtopic.id} subtopic={subtopic} onCompletion={onCompletion} saving={saving} />)}</div><TopicTests topic={topic} /></div></div>;

};

const SubtopicSection = ({ subtopic, onCompletion, saving }: { subtopic: ContentSubtopic; onCompletion: (id: string, completed: boolean) => void; saving: boolean }) => {
  const [isOpen, setIsOpen] = useState(false);
  return <Card className="overflow-hidden">
    <button onClick={() => setIsOpen((open) => !open)} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left transition hover:bg-moss-50/60">
      <div className="min-w-0"><h3 className="font-semibold text-ink">{subtopic.name}</h3><p className="mt-1 truncate text-xs text-stone-400">{subtopic.description}</p></div>
      <div className="flex shrink-0 items-center gap-3"><Badge className="bg-moss-50 text-moss-800">{subtopic.completedContentCount}/{subtopic.totalContentCount}</Badge><ChevronDown size={18} className={cn('text-stone-400 transition-transform', isOpen && 'rotate-180')} /></div>
    </button>
    {isOpen && <div className="divide-y divide-stone-100 border-t border-stone-100">{subtopic.contents.map((content) => <LessonRow key={content.id} content={content} onCompletion={onCompletion} saving={saving} />)}</div>}
  </Card>;
};

const LessonRow = ({ content, onCompletion, saving }: { content: LearningContent; onCompletion: (id: string, completed: boolean) => void; saving: boolean }) => { const Icon = contentVisual[content.contentType]; return <div className={cn('flex flex-col gap-3 px-4 py-3 sm:flex-row sm:items-center sm:px-5', !content.hasAccess && 'bg-stone-50/70')}><div className="relative grid size-10 shrink-0 place-items-center overflow-hidden rounded-xl bg-gradient-to-br from-moss-100 to-lime/35 text-moss-700">{content.thumbnailUrl ? <img src={content.thumbnailUrl} alt="" className="size-full object-cover" /> : <Icon size={19} />}{!content.hasAccess && <div className="absolute inset-0 grid place-items-center bg-moss-950/45 text-white"><Lock size={15} /></div>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-semibold text-ink">{content.title}</p>{content.completed && <Badge className="bg-moss-100 text-moss-800"><Check size={12} />Completed</Badge>}{!content.hasAccess && <Badge className="bg-stone-200 text-stone-600">Locked</Badge>}</div><div className="mt-1 flex flex-wrap gap-3 text-xs text-stone-400"><span>{content.contentType.replace('_', ' ')}</span>{content.estimatedDurationMinutes && <span>{content.estimatedDurationMinutes} min</span>}{content.isFree && <span className="font-semibold text-moss-700">Free</span>}</div></div><div className="flex shrink-0 gap-2"><Button variant="outline" size="sm" disabled={!content.hasAccess} onClick={() => { if (content.contentUrl) window.open(content.contentUrl, '_blank', 'noopener,noreferrer'); }}><PlayCircle size={15} />Open</Button><Button size="sm" variant={content.completed ? 'secondary' : 'primary'} disabled={!content.hasAccess || saving} onClick={() => onCompletion(content.id, !content.completed)}>{content.completed ? 'Undo' : 'Complete'}</Button></div></div>; };

const TopicTests = ({ topic }: { topic: ContentTopic }) => <section><div className="mb-3 flex items-center gap-2"><Sparkles size={17} className="text-amber" /><h2 className="text-lg font-bold text-ink">Topic practice</h2></div>{topic.tests.length ? <div className="grid gap-4 lg:grid-cols-2">{topic.tests.map((test) => <Card key={test.id} className="p-5"><div className="flex gap-2"><div className="min-w-0 flex-1"><h3 className="font-semibold text-ink">{test.name}</h3><p className="mt-1 text-sm leading-5 text-stone-500">{test.description}</p></div><Badge className={test.isFree ? 'bg-lime/45 text-moss-900' : test.hasAccess ? 'bg-moss-100 text-moss-800' : 'bg-stone-100 text-stone-500'}>{test.isFree ? 'Free' : test.hasAccess ? 'Included' : 'Locked'}</Badge></div><div className="mt-4 flex flex-wrap gap-3 text-xs text-stone-500"><span>{test.totalQuestions} questions</span><span>{test.durationMinutes} min</span><span>{test.totalMarks} marks</span><span>{test.difficulty}</span></div><Button className="mt-5" size="sm" variant={test.hasAccess ? 'secondary' : 'outline'} disabled><PlayCircle size={15} />{test.hasAccess ? 'Attempt soon' : 'Locked'}</Button></Card>)}</div> : <Card className="border-dashed p-5 text-sm text-stone-500">No practice test has been added for this topic yet.</Card>}</section>;

const AttemptsPanel = ({ attempts }: { attempts: ReturnType<typeof useQuery<{ attempts: ContentAttempt[] }>> }) => { if (attempts.isLoading) return <div className="space-y-4">{Array.from({ length: 3 }, (_, index) => <Skeleton key={index} className="h-44" />)}</div>; if (attempts.isError) return <EmptyState icon={Trophy} title="Could not load attempted tests" description="Please refresh the page and try again." />; if (!attempts.data?.attempts.length) return <EmptyState icon={Trophy} title="No topic tests attempted yet" description="Your completed and in-progress practice tests will be available here." />; return <div className="space-y-4">{attempts.data.attempts.map((attempt) => <Card key={attempt.id} className="p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-bold text-ink">{attempt.test.name}</h2><Badge className={attempt.status === 'IN_PROGRESS' ? 'bg-amber/20 text-[#98670e]' : 'bg-moss-100 text-moss-800'}>{attempt.status.replace('_', ' ')}</Badge></div><p className="mt-1 text-sm text-stone-500">{attempt.test.subject} · {attempt.test.topic}</p><div className="mt-4 grid grid-cols-2 gap-x-7 gap-y-2 text-sm sm:grid-cols-4"><Metric label="Score" value={`${attempt.marksScored}/${attempt.totalMarks}`} /><Metric label="Accuracy" value={`${Math.round(attempt.accuracy)}%`} /><Metric label="Time used" value={formatDuration(attempt.timeTakenSeconds)} /><Metric label="Questions" value={`${attempt.correctAnswers} correct`} /></div><p className="mt-4 text-xs text-stone-400">Started {formatDateTime(attempt.startedAt)}{attempt.submittedAt ? ` · Submitted ${formatDateTime(attempt.submittedAt)}` : ''}</p></div><div className="min-w-60 rounded-2xl bg-stone-50 p-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-stone-400">Section performance</p><div className="mt-3 space-y-2">{attempt.sections.map((section) => <div key={section.id} className="flex items-center justify-between gap-3 text-sm"><span className="truncate text-stone-600">{section.name}</span><span className="font-semibold text-moss-800">{section.marksScored}/{section.totalMarks}</span></div>)}</div></div></div></Card>)}</div>; };
const Metric = ({ label, value }: { label: string; value: string }) => <div><p className="text-xs text-stone-400">{label}</p><p className="mt-0.5 font-semibold text-ink">{value}</p></div>;
const ContentSkeleton = () => <div className="space-y-7"><Skeleton className="h-24 w-full max-w-2xl" /><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }, (_, index) => <Skeleton key={index} className="h-80" />)}</div></div>;
