import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BookOpenCheck, Check, ChevronRight, Clock3, FileText, Globe2, Layers3, Lock, PlayCircle, Sparkles, Video } from 'lucide-react';

import { EmptyState } from '../../../components/empty-state';
import { Badge } from '../../../components/ui/badge';
import { Button } from '../../../components/ui/button';
import { Card } from '../../../components/ui/card';
import { Skeleton } from '../../../components/ui/skeleton';
import { api } from '../../../lib/api';
import { cn } from '../../../lib/utils';
import type { ContentSubtopic, ContentSubject, ContentTopic, ContentTreeResponse, LearningContent } from './types';

const percent = (done: number, total: number) => total ? Math.round((done / total) * 100) : 0;
const contentVisual = { YOUTUBE: Video, PDF: FileText, DOCUMENT: BookOpenCheck, WEBSITE: Globe2 };

export const ContentPage = () => {
  const queryClient = useQueryClient();
  const [subjectId, setSubjectId] = useState<string>();
  const [topicId, setTopicId] = useState<string>();
  const learning = useQuery({ queryKey: ['learning-content'], queryFn: () => api<ContentTreeResponse>('/api/v1/content') });
  const updateCompletion = useMutation({
    mutationFn: ({ contentId, completed }: { contentId: string; completed: boolean }) => api(`/api/v1/content/contents/${contentId}/completion`, { method: 'PATCH', body: JSON.stringify({ completed }) }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['learning-content'] }),
  });
  if (learning.isLoading) return <ContentSkeleton />;
  if (learning.isError || !learning.data) return <EmptyState icon={BookOpenCheck} title="Could not load learning content" description="Please refresh the page and try again." />;
  const subjects = learning.data.subjects;
  if (!subjects.length) return <EmptyState icon={BookOpenCheck} title="Learning library is on its way" description="There are no active learning resources yet." />;
  const subject = subjects.find((item) => item.id === subjectId) ?? subjects[0];
  const topic = subject.topics.find((item) => item.id === topicId) ?? subject.topics[0];
  const completed = subjects.reduce((sum, item) => sum + item.completedContentCount, 0);
  const total = subjects.reduce((sum, item) => sum + item.totalContentCount, 0);
  return <div className="space-y-7">
    <section className="relative overflow-hidden rounded-3xl bg-moss-900 px-6 py-7 text-white shadow-float sm:px-8">
      <div className="absolute -right-12 -top-20 size-64 rounded-full bg-lime/15 blur-3xl" />
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-lime">Learning library</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Build understanding, one lesson at a time.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-moss-100/75">Follow your subject path, keep your learning streak visible, and reinforce each topic with a practice test.</p></div><div className="rounded-2xl border border-white/10 bg-white/10 px-5 py-4 backdrop-blur"><p className="text-xs text-moss-100/70">Overall completion</p><p className="mt-1 text-2xl font-bold">{percent(completed, total)}%</p><p className="text-xs text-moss-100/70">{completed} of {total} resources complete</p></div></div>
    </section>
    <div className="grid gap-6 xl:grid-cols-[260px_minmax(0,1fr)]">
      <Card className="h-fit p-3"><p className="px-3 pb-2 pt-1 text-xs font-bold uppercase tracking-[.16em] text-stone-400">Subjects</p>{subjects.map((item) => <button key={item.id} onClick={() => { setSubjectId(item.id); setTopicId(undefined); }} className={cn('w-full rounded-2xl px-3 py-3 text-left transition', item.id === subject.id ? 'bg-moss-800 text-white shadow-sm' : 'text-stone-600 hover:bg-moss-50')}><span className="block text-sm font-semibold">{item.name}</span><span className={cn('mt-1 block text-xs', item.id === subject.id ? 'text-moss-100/70' : 'text-stone-400')}>{item.completedContentCount}/{item.totalContentCount} complete</span><div className={cn('mt-2 h-1.5 overflow-hidden rounded-full', item.id === subject.id ? 'bg-white/15' : 'bg-stone-100')}><div className="h-full rounded-full bg-lime" style={{ width: `${percent(item.completedContentCount, item.totalContentCount)}%` }} /></div></button>)}</Card>
      <div className="min-w-0 space-y-6"><div className="flex flex-wrap items-center gap-2 text-sm text-stone-500"><span>{subject.name}</span><ChevronRight size={15} /><span className="font-medium text-ink">{topic?.name ?? 'Topics'}</span></div><div className="flex gap-2 overflow-x-auto pb-1">{subject.topics.map((item) => <button key={item.id} onClick={() => setTopicId(item.id)} className={cn('shrink-0 rounded-xl border px-4 py-3 text-left transition', item.id === topic?.id ? 'border-moss-700 bg-moss-50 text-moss-900' : 'border-stone-200 bg-white text-stone-600 hover:border-moss-200')}><span className="block text-sm font-semibold">{item.name}</span><span className="mt-1 block text-xs text-stone-400">{percent(item.completedContentCount, item.totalContentCount)}% complete</span></button>)}</div>
        {topic ? <TopicView topic={topic} onCompletion={(contentId, completed) => updateCompletion.mutate({ contentId, completed })} saving={updateCompletion.isPending} /> : <EmptyState icon={Layers3} title="No topics available" description="Resources will appear here when this subject is published." />}
      </div>
    </div>
  </div>;
};

const TopicView = ({ topic, onCompletion, saving }: { topic: ContentTopic; onCompletion: (id: string, completed: boolean) => void; saving: boolean }) => <div className="grid gap-6 2xl:grid-cols-[minmax(0,1fr)_310px]"><div className="space-y-5"><Card className="p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-moss-700">Current topic</p><h2 className="mt-1 text-2xl font-bold text-ink">{topic.name}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-500">{topic.description}</p></div><div className="min-w-32"><p className="text-right text-sm font-bold text-moss-800">{percent(topic.completedContentCount, topic.totalContentCount)}%</p><div className="mt-2 h-2 overflow-hidden rounded-full bg-moss-100"><div className="h-full rounded-full bg-lime" style={{ width: `${percent(topic.completedContentCount, topic.totalContentCount)}%` }} /></div><p className="mt-1 text-right text-xs text-stone-400">{topic.completedContentCount}/{topic.totalContentCount} lessons</p></div></div></Card>{topic.subtopics.map((subtopic) => <SubtopicSection key={subtopic.id} subtopic={subtopic} onCompletion={onCompletion} saving={saving} />)}</div><aside className="space-y-4"><Card className="p-5"><div className="flex items-center gap-2"><Sparkles size={17} className="text-amber" /><h3 className="font-semibold text-ink">Topic practice</h3></div><p className="mt-2 text-sm leading-6 text-stone-500">Reinforce what you learn with a focused topic test.</p><div className="mt-4 space-y-3">{topic.tests.length ? topic.tests.map((test) => <div key={test.id} className="rounded-2xl border border-stone-100 p-4"><div className="flex gap-2"><p className="min-w-0 flex-1 text-sm font-semibold text-ink">{test.name}</p><Badge className={test.isFree ? 'bg-lime/45 text-moss-900' : test.hasAccess ? 'bg-moss-100 text-moss-800' : 'bg-stone-100 text-stone-500'}>{test.isFree ? 'Free' : test.hasAccess ? 'Included' : 'Locked'}</Badge></div><p className="mt-1 text-xs leading-5 text-stone-500">{test.description}</p><div className="mt-3 flex gap-3 text-xs text-stone-500"><span>{test.totalQuestions} questions</span><span>{test.durationMinutes} min</span></div><Button className="mt-4 w-full" size="sm" variant={test.hasAccess ? 'secondary' : 'outline'} disabled><PlayCircle size={15} />{test.hasAccess ? 'Attempt soon' : 'Locked'}</Button></div>) : <p className="rounded-xl bg-stone-50 p-3 text-sm text-stone-500">No topic test has been added yet.</p>}</div></Card><Card className="bg-moss-50 p-5 shadow-none"><Clock3 size={18} className="text-moss-700" /><p className="mt-3 text-sm font-semibold text-moss-900">{topic.estimatedDurationMinutes} min learning path</p><p className="mt-1 text-xs leading-5 text-moss-700/70">Complete every unlocked resource to finish this topic.</p></Card></aside></div>;

const SubtopicSection = ({ subtopic, onCompletion, saving }: { subtopic: ContentSubtopic; onCompletion: (id: string, completed: boolean) => void; saving: boolean }) => <Card className="overflow-hidden"><div className="flex items-center justify-between border-b border-stone-100 px-5 py-4"><div><h3 className="font-semibold text-ink">{subtopic.name}</h3><p className="mt-1 text-xs text-stone-400">{subtopic.description}</p></div><Badge className="bg-moss-50 text-moss-800">{subtopic.completedContentCount}/{subtopic.totalContentCount}</Badge></div><div className="divide-y divide-stone-100">{subtopic.contents.map((content) => <LessonRow key={content.id} content={content} onCompletion={onCompletion} saving={saving} />)}</div></Card>;

const LessonRow = ({ content, onCompletion, saving }: { content: LearningContent; onCompletion: (id: string, completed: boolean) => void; saving: boolean }) => { const Icon = contentVisual[content.contentType]; return <div className={cn('flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:p-5', !content.hasAccess && 'bg-stone-50/70')}><div className="relative h-28 w-full shrink-0 overflow-hidden rounded-2xl bg-gradient-to-br from-moss-100 to-lime/35 sm:w-40">{content.thumbnailUrl ? <img src={content.thumbnailUrl} alt="" className="size-full object-cover" /> : <div className="grid size-full place-items-center text-moss-700"><Icon size={28} /></div>}{!content.hasAccess && <div className="absolute inset-0 grid place-items-center bg-moss-950/45 text-white"><Lock size={20} /></div>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-ink">{content.title}</p>{content.completed && <Badge className="bg-moss-100 text-moss-800"><Check size={12} />Completed</Badge>}{!content.hasAccess && <Badge className="bg-stone-200 text-stone-600">Locked</Badge>}</div><p className="mt-1 line-clamp-2 text-sm leading-5 text-stone-500">{content.description}</p><div className="mt-2 flex flex-wrap gap-3 text-xs text-stone-400"><span>{content.contentType.replace('_', ' ')}</span>{content.estimatedDurationMinutes && <span>{content.estimatedDurationMinutes} min</span>}{content.isFree && <span className="font-semibold text-moss-700">Free resource</span>}</div></div><div className="flex shrink-0 gap-2"><Button variant="outline" size="sm" disabled={!content.hasAccess} onClick={() => { if (content.contentUrl) window.open(content.contentUrl, '_blank', 'noopener,noreferrer'); }}><PlayCircle size={15} />Open</Button><Button size="sm" variant={content.completed ? 'secondary' : 'primary'} disabled={!content.hasAccess || saving} onClick={() => onCompletion(content.id, !content.completed)}>{content.completed ? 'Undo' : 'Complete'}</Button></div></div>; };

const ContentSkeleton = () => <div className="space-y-7"><Skeleton className="h-48" /><div className="grid gap-6 xl:grid-cols-[260px_1fr]"><Skeleton className="h-72" /><div className="space-y-5"><Skeleton className="h-28" />{Array.from({ length: 3 }, (_, index) => <Skeleton key={index} className="h-40" />)}</div></div></div>;
