import type { Response } from 'express';
import type { AuthenticatedRequest } from '../../shared/auth/auth.middleware.js';
import * as service from './mentorship.service.js';
export const listPrograms = async (request: AuthenticatedRequest, response: Response) => response.json({ programs: await service.programs(request.auth!.sub) });
export const listBatches = async (request: AuthenticatedRequest, response: Response) => response.json({ batches: await service.batches(request.auth!.sub, String(request.params.programId)) });
export const batchOverview = async (request: AuthenticatedRequest, response: Response) => response.json({ batch: await service.overview(request.auth!.sub, String(request.params.batchId)) });
export const taskCompletion = async (request: AuthenticatedRequest, response: Response) => response.json({ task: await service.setTaskCompletion(request.auth!.sub, String(request.params.taskId), request.body.completed) });
export const sessionJoin = async (request: AuthenticatedRequest, response: Response) => response.json({ session: await service.joinSession(request.auth!.sub, String(request.params.sessionId)) });
export const doubts = async (request: AuthenticatedRequest, response: Response) => response.json({ doubts: await service.listDoubts(request.auth!.sub, String(request.params.batchId)) });
export const createDoubt = async (request: AuthenticatedRequest, response: Response) => response.status(201).json({ doubt: await service.createDoubt(request.auth!.sub, String(request.params.batchId), request.body) });
export const doubtReplies = async (request: AuthenticatedRequest, response: Response) => response.json({ replies: await service.replies(request.auth!.sub, String(request.params.doubtId)) });
export const createReply = async (request: AuthenticatedRequest, response: Response) => response.status(201).json({ reply: await service.addReply(request.auth!.sub, String(request.params.doubtId), request.body) });
export const satisfied = async (request: AuthenticatedRequest, response: Response) => response.json({ doubt: await service.setSatisfied(request.auth!.sub, String(request.params.doubtId), request.body.isSatisfied) });
