import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { MessageCirclePlus } from 'lucide-react';
import { Button } from '../../../components/ui/button';
import { Card } from '../../../components/ui/card';
import { Badge } from '../../../components/ui/badge';
import { EmptyState } from '../../../components/empty-state';
import { api } from '../../../lib/api';
import { formatDateTime } from '../../../lib/utils';

type Doubt = { id: string; title: string; description: string; visibility: 'PUBLIC' | 'PRIVATE'; status: string; isSatisfied: boolean; createdAt: string; student: { name: string }; _count: { replies: number } };
export const DoubtsPage = () => {
  const { batchId = '' } = useParams(); const client = useQueryClient(); const [open, setOpen] = useState(false); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [visibility, setVisibility] = useState<'PUBLIC' | 'PRIVATE'>('PUBLIC');
  const doubts = useQuery({ queryKey: ['mentorship-doubts', batchId], queryFn: () => api<{ doubts: Doubt[] }>(`/api/v1/mentorship/batches/${batchId}/doubts`) });
  const create = useMutation({ mutationFn: () => api(`/api/v1/mentorship/batches/${batchId}/doubts`, { method: 'POST', body: JSON.stringify({ title, description, visibility }) }), onSuccess: () => { setOpen(false); setTitle(''); setDescription(''); client.invalidateQueries({ queryKey: ['mentorship-doubts', batchId] }); } });
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><Link className="text-sm font-semibold text-moss-700" to={`/student/mentorship/batches/${batchId}`}>← Batch dashboard</Link><p className="mt-4 eyebrow">Batch discussion</p><h1 className="text-3xl font-bold">Doubts</h1><p className="mt-2 text-sm text-stone-500">Ask publicly for peer support, or privately for mentor-only help.</p></div><Button onClick={() => setOpen((value) => !value)}><MessageCirclePlus size={16} />Ask a doubt</Button></div>{open && <Card className="p-5"><input value={title} onChange={(event) => setTitle(event.target.value)} className="focus-ring w-full rounded-xl border border-stone-200 px-3 py-2.5" placeholder="Write a clear title" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} className="focus-ring mt-3 min-h-32 w-full rounded-xl border border-stone-200 p-3" placeholder="Describe your question with enough context…" /><div className="mt-3 flex flex-wrap items-center gap-3"><select value={visibility} onChange={(event) => setVisibility(event.target.value as 'PUBLIC' | 'PRIVATE')} className="rounded-xl border border-stone-200 bg-white px-3 py-2 text-sm"><option value="PUBLIC">Public — batch students can reply</option><option value="PRIVATE">Private — only your mentors can reply</option></select><Button disabled={!title.trim() || !description.trim() || create.isPending} onClick={() => create.mutate()}>{create.isPending ? 'Posting…' : 'Post doubt'}</Button></div></Card>}{doubts.data?.doubts.length ? <div className="space-y-4">{doubts.data.doubts.map((doubt) => <Card key={doubt.id} className="p-5"><div className="flex flex-wrap gap-2"><h2 className="mr-auto font-bold text-ink">{doubt.title}</h2><Badge className={doubt.visibility === 'PUBLIC' ? 'bg-sky-100 text-sky-800' : 'bg-stone-100 text-stone-600'}>{doubt.visibility}</Badge><Badge className={doubt.isSatisfied ? 'bg-moss-100 text-moss-800' : 'bg-amber/20 text-[#93620c]'}>{doubt.isSatisfied ? 'Satisfied' : doubt.status}</Badge></div><p className="mt-3 text-sm leading-6 text-stone-600">{doubt.description}</p><p className="mt-4 text-xs text-stone-400">{doubt.student.name} · {formatDateTime(doubt.createdAt)} · {doubt._count.replies} replies</p></Card>)}</div> : <EmptyState icon={MessageCirclePlus} title="No doubts yet" description="Start the conversation when you need help with a concept or question." />}</div>;
};
